AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  starkbank-invoice-creation

  SAM Template for starkbank-invoice-creation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Parameters:
  MinInvoiceQuantity:
    Type: Number
    Description: Minimun amount of invoices that will be created on execution
    Default: 8
  MaxInvoiceQuantity:
    Type: Number
    Description: Maximun amount of invoices that will be created on execution
    Default: 12
  StarkbankSecretsId:
    Type: String
    Description: ID of Secret where is stored Starkbank Project ID and Private Key
  StarkbankEnvironment:
    Type: String
    Default: sandbox
    Description: Starkbank environment where the invoices will be created
    AllowedValues:
      - sandbox
      - production
  InvoicesTag:
    Type: String
    Default: test-saulo
    Description: Tag that will be passed on created invoices
  LogLevel:
    Type: String
    Default: INFO
    Description: Level of logs that will be emitted by lambda
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL

Resources:
  StarkbankInvoiceCreation:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: rate(3 hours)
            Name: SchedulerInvoiceCreation
      Environment:
        Variables:
          STARKBANK_ENVIRONMENT: !Ref StarkbankEnvironment
          STARKBANK_PROJECT_ID: !Sub
            - "{{resolve:secretsmanager:arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${StarkbankSecretsId}:SecretString:PROJECT_ID}}"
            - StarkbankSecretsId: !Ref StarkbankSecretsId
          STARKBANK_PRIVATE_KEY_CONTENT: !Sub
            - "{{resolve:secretsmanager:arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${StarkbankSecretsId}:SecretString:PRIVATE_KEY}}"
            - StarkbankSecretsId: !Ref StarkbankSecretsId
          INVOICES_TAG: !Ref InvoicesTag
          MIN_INVOICES_QUANTITY: !Ref MinInvoiceQuantity
          MAX_INVOICES_QUANTITY: !Ref MaxInvoiceQuantity
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub
              - "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${StarkbankSecretsId}"
              - StarkbankSecretsId: !Ref StarkbankSecretsId

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StarkbankInvoiceCreation:
    Description: "Starkbank Invoice Creation Lambda Function ARN"
    Value: !GetAtt StarkbankInvoiceCreation.Arn
  StarkbankInvoiceCreationIamRole:
    Description: "Implicit IAM Role created Starkbank Invoice Creation"
    Value: !GetAtt StarkbankInvoiceCreationRole.Arn
  Scheduler:
    Description: "Starkbank Invoice Creation Event Schedule ARN"
    Value: !GetAtt StarkbankInvoiceCreationScheduler.Arn
